dataconnector:
  athena:
    uri: http://development-hasura-connector.equfmc.easypanel.host/api/v1/athena
  mariadb:
    uri: http://development-hasura-connector.equfmc.easypanel.host/api/v1/mariadb
  mysql8:
    uri: http://development-hasura-connector.equfmc.easypanel.host/api/v1/mysql
  oracle:
    uri: http://development-hasura-connector.equfmc.easypanel.host/api/v1/oracle
  snowflake:
    uri: http://development-hasura-connector.equfmc.easypanel.host/api/v1/snowflake
